default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_DEV_USER'] %>
  password: <%= ENV['DATABASE_DEV_PASSWORD'] %>
  socket: /tmp/mysql.sock


development:
  <<: *default
  database:  onalog_development

test:
  <<: *default
  database:  onalog_app_test

production:
  <<: *default
  database: onalog_app_production
